package com.bunkmeter.app.scheduler;

import android.app.Application;
import android.content.Context;

import androidx.annotation.NonNull;
import androidx.work.Worker;
import androidx.work.WorkerParameters;

import com.bunkmeter.app.database.TempReadingStorage;
import com.bunkmeter.app.model.AttendanceStatus;
import com.bunkmeter.app.notifications.AttendanceNotificationHelper;
import com.bunkmeter.app.repository.AttendanceRepository;

/**
 * Runs after all three {@link LocationReadingWorker} workers have finished.
 *
 * <h3>Decision logic</h3>
 * Reads the accumulated confidence score from {@link TempReadingStorage} and
 * applies the following threshold:
 * <ul>
 *   <li><strong>Score ≥ 80 pts</strong> → the student is reliably detected
 *       inside the classroom; the DB row is updated to
 *       {@link AttendanceStatus#PRESENT} automatically.</li>
 *   <li><strong>Score &lt; 80 pts</strong> → GPS confidence was insufficient;
 *       a fallback notification is shown so the student can confirm manually.</li>
 * </ul>
 *
 * <h3>Why 80?</h3>
 * A single "good" reading (≤15 m accuracy = 60 pts) is not enough on its own
 * because indoor GPS can be optimistic.  Two good readings (120 pts) or one
 * excellent reading (100 pts) cross the threshold, which mirrors the old
 * "2 valid readings" rule but is far more nuanced.
 */
public class EvaluationWorker extends Worker {

    /** Minimum cumulative score required to auto-mark the student PRESENT. */
    private static final int PRESENCE_THRESHOLD = 80;

    public EvaluationWorker(@NonNull Context context,
                            @NonNull WorkerParameters workerParams) {
        super(context, workerParams);
    }

    @NonNull
    @Override
    public Result doWork() {
        final long   lectureId  = getInputData().getLong("lecture_id",  -1);
        final int    subjectId  = getInputData().getInt("subject_id",   -1);
        final int    startTime  = getInputData().getInt("start_time",   -1);
        final String date       = getInputData().getString("date");
        // Deterministic session ID generated by AttendanceScheduler for this lecture
        final int    sessionId  = getInputData().getInt("session_id",    0);

        if (lectureId == -1 || subjectId == -1 || startTime == -1 || date == null) {
            return Result.failure();
        }

        // Sum the confidence points collected across all reading slots
        int totalScore = TempReadingStorage.getTotalScore(getApplicationContext(), lectureId);

        if (totalScore >= PRESENCE_THRESHOLD) {
            // Enough confidence — auto-mark PRESENT without bothering the student
            AttendanceRepository repo =
                    new AttendanceRepository((Application) getApplicationContext());
            repo.updateAttendanceStatus(
                    subjectId, date, startTime, 0, AttendanceStatus.PRESENT);
        } else {
            // Not confident enough — ask the student via a fallback notification
            AttendanceNotificationHelper.triggerFallbackNotification(
                    getApplicationContext(),
                    lectureId, subjectId, date, startTime, sessionId);
        }

        // Always wipe temporary storage to prevent SharedPreference bloat
        TempReadingStorage.clearReadings(getApplicationContext(), lectureId);

        return Result.success();
    }
}