package com.bunkmeter.app.receiver;

import android.app.Application;
import android.app.NotificationManager;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;

import com.bunkmeter.app.model.AttendanceStatus;
import com.bunkmeter.app.repository.AttendanceRepository;
import com.bunkmeter.app.service.AttendanceForegroundService;

/**
 * Handles the action buttons on both the foreground ("Lecture in Progress!")
 * notification and the fallback ("Are you in class?") notification.
 *
 * <h3>Changes from the old implementation</h3>
 * <ul>
 *   <li><strong>No more magic integers.</strong>  All status values are passed
 *       as {@link AttendanceStatus} enum constants rather than raw 0 / 1 / 2
 *       literals, making the intent of each branch immediately clear.</li>
 *   <li><strong>Explicit notification cancellation.</strong>  The Intent now
 *       carries a {@code "notification_id"} extra (populated by
 *       {@link com.bunkmeter.app.notifications.AttendanceNotificationHelper}
 *       and by {@link AttendanceForegroundService}).  The receiver reads this
 *       ID and calls {@link NotificationManager#cancel(int)} immediately so the
 *       notification disappears the moment the user taps a button — no dangling
 *       UI elements.</li>
 *   <li><strong>Foreground service lifecycle.</strong>  The blanket
 *       {@code stopService()} is still called after the action is handled
 *       because the service is single-instance per active lecture.  A future
 *       improvement could pass the service's {@code startId} for a fully
 *       scoped stop.</li>
 * </ul>
 */
public class AttendanceActionReceiver extends BroadcastReceiver {

    @Override
    public void onReceive(Context context, Intent intent) {
        if (intent == null || intent.getAction() == null) return;

        // --- Extract payload ---
        int    subjectId     = intent.getIntExtra("subject_id",      -1);
        int    startTime     = intent.getIntExtra("start_time",      -1);
        String date          = intent.getStringExtra("date");
        // Deterministic hash generated by the notification helper or the service
        int    notificationId = intent.getIntExtra("notification_id", -1);

        if (subjectId == -1 || date == null) return;

        // --- Dismiss the notification immediately ---
        // This removes the card from the notification tray the instant the user
        // taps a button, preventing "ghost" notifications.
        if (notificationId != -1) {
            NotificationManager nm =
                    (NotificationManager) context.getSystemService(Context.NOTIFICATION_SERVICE);
            if (nm != null) {
                nm.cancel(notificationId);
            }
        }

        // --- Persist the attendance status using typed enum constants ---
        Application app = (Application) context.getApplicationContext();
        AttendanceRepository repository = new AttendanceRepository(app);

        switch (intent.getAction()) {
            case "ACTION_PRESENT":
                repository.updateAttendanceStatus(
                        subjectId, date, startTime, 0, AttendanceStatus.PRESENT);
                break;

            case "ACTION_BUNK":
                repository.updateAttendanceStatus(
                        subjectId, date, startTime, 0, AttendanceStatus.BUNK);
                break;

            case "ACTION_CANCEL":
                repository.updateAttendanceStatus(
                        subjectId, date, startTime, 0, AttendanceStatus.CANCELLED);
                break;

            default:
                return; // Unknown action — do nothing
        }

        // --- Stop the foreground service ---
        // The service is single-instance; stopping it here is safe because the
        // user has already committed to a status (PRESENT / BUNK / CANCELLED).
        Intent stopServiceIntent =
                new Intent(context, AttendanceForegroundService.class);
        context.stopService(stopServiceIntent);
    }
}